iq_server:
  image: "sonatype/nexus-iq-server"
  tag: "1.186.0"
  licenseSecret: nx-license
  database:
    hostname: "172.17.0.1"
    name: "kind_iqhadb"
    password: "iq123"
    username: "iq"
  persistence:
    enabled: true
    size: 2G
    persistentVolumeName: ""
    storageClassName: "nfs"
  replicas: 2
  ingress:
    enabled: true
    hostApplication: "iqha1.mydomain"
    hostAdmin: "iqha1-admin.mydomain"
iq_server_jobs:
  migrationJobAnnotations:
    # Annotations to apply to the DB migration job
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    "helm.sh/hook-weight": "0"
